name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - 'packages/shared/**'
      - 'infrastructure/backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build -w @path-to-glory/shared

      - name: Build backend
        run: npm run build -w @path-to-glory/backend

      - name: Package Lambda function
        run: |
          cd packages/backend

          # Copy GraphQL schema to dist
          mkdir -p dist
          cp ../shared/src/schema/schema.graphql dist/schema.graphql

          # Install production dependencies
          npm ci --production

          # Create deployment package
          cd dist
          zip -r ../lambda.zip .

          # Add node_modules to the zip
          cd ..
          zip -r lambda.zip node_modules

          echo "Lambda package size: $(du -h lambda.zip | cut -f1)"

          # Verify contents
          echo "Package contents:"
          unzip -l lambda.zip | head -25

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Verify AWS credentials
        run: |
          echo "Testing AWS credentials and role assumption..."
          aws sts get-caller-identity
          echo "✓ AWS credentials verified"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          cd infrastructure/backend
          terraform init

      - name: Terraform Plan
        env:
          TF_VAR_cognito_user_pool_id: ${{ secrets.COGNITO_USER_POOL_ID }}
          TF_VAR_cognito_client_id: ${{ secrets.COGNITO_CLIENT_ID }}
        run: |
          cd infrastructure/backend
          terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_cognito_user_pool_id: ${{ secrets.COGNITO_USER_POOL_ID }}
          TF_VAR_cognito_client_id: ${{ secrets.COGNITO_CLIENT_ID }}
        run: |
          cd infrastructure/backend
          terraform apply -auto-approve tfplan

      - name: Get GraphQL URL
        id: outputs
        run: |
          cd infrastructure/backend
          GRAPHQL_URL=$(terraform output -raw graphql_url)
          echo "graphql_url=$GRAPHQL_URL" >> $GITHUB_OUTPUT
          echo "### 🚀 Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**GraphQL Endpoint:** $GRAPHQL_URL" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test with:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "curl -X POST $GRAPHQL_URL \\" >> $GITHUB_STEP_SUMMARY
          echo '  -H "Content-Type: application/json" \' >> $GITHUB_STEP_SUMMARY
          echo '  -d '"'"'{"query":"{ factions { id name } }"}'"'"'' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Smoke test
        run: |
          cd infrastructure/backend
          GRAPHQL_URL=$(terraform output -raw graphql_url)
          echo "Testing GraphQL endpoint: $GRAPHQL_URL"
          echo ""

          # Wait for DNS propagation and API Gateway to be ready
          echo "Waiting for API Gateway to be ready (up to 5 minutes)..."
          MAX_RETRIES=10
          RETRY_DELAY=30

          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i/$MAX_RETRIES..."

            # Use -f to fail on HTTP errors, -s for silent, -S to show errors
            RESPONSE=$(curl -f -s -S -X POST "$GRAPHQL_URL" \
              -H "Content-Type: application/json" \
              -d '{"query":"{ factions { id name } }"}' 2>&1) && SUCCESS=true || SUCCESS=false

            if [ "$SUCCESS" = true ]; then
              echo "Response: $RESPONSE"

              # Check if response contains data
              if echo "$RESPONSE" | grep -q '"data"'; then
                echo ""
                echo "✅ Smoke test passed!"
                exit 0
              else
                echo "⚠️  Got response but no data field. Response: $RESPONSE"
              fi
            else
              echo "⚠️  Request failed: $RESPONSE"
            fi

            if [ $i -lt $MAX_RETRIES ]; then
              echo "Waiting ${RETRY_DELAY}s before retry..."
              sleep $RETRY_DELAY
            fi
          done

          echo ""
          echo "❌ Smoke test failed after $MAX_RETRIES attempts"
          echo "This may be due to DNS propagation delay or API Gateway setup."
          echo "The deployment was successful - try testing manually in a few minutes:"
          echo "  curl -X POST $GRAPHQL_URL -H 'Content-Type: application/json' -d '{\"query\":\"{ factions { id name } }\"}'"
          exit 1
